version: "3"
services:
  backend:
    build: ./backend
    command: python app/main.py
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080

  frontend:
    build: ./frontend
    command: yarn start
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000