import os


GAME_ROUNDS_COUNT: int = os.getenv("RPS_GAME_ROUNDS_COUNT", 1)
GAME_PLAYERS_COUNT: int = os.getenv("RPS_GAME_PLAYERS_COUNT", 2)
GAME_ROUND_DURATION: int = os.getenv("RPS_GAME_ROUND_DURATION", 10)
